package org.cuatrovientos.signum.app;

import android.app.Application;

import org.cuatrovientos.signum.R;
import org.cuatrovientos.signum.models.Categoria;
import org.cuatrovientos.signum.models.Signo;
import org.cuatrovientos.signum.models.SignoPracticado;

import java.util.concurrent.atomic.AtomicInteger;

import io.realm.Realm;
import io.realm.RealmConfiguration;
import io.realm.RealmObject;
import io.realm.RealmResults;

public class MyApplication extends Application {

    public static AtomicInteger signosId = new AtomicInteger();
    public static AtomicInteger categoriasId = new AtomicInteger();
    public static AtomicInteger signoPracticadoID = new AtomicInteger();


    @Override
    public void onCreate() {
        super.onCreate();

        setUpRealmConfig();
        Realm realm = Realm.getDefaultInstance();
        signosId = getIdByTable(realm, Signo.class);
        categoriasId = getIdByTable(realm, Categoria.class);
        signoPracticadoID = getIdByTableS(realm, SignoPracticado.class);
        realm.close();
    }

    private void setUpRealmConfig(){
        Realm.init(getApplicationContext());
        RealmConfiguration config = new RealmConfiguration
                .Builder()
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(config);
    }

        private <SignoPracticado extends RealmObject> AtomicInteger getIdByTableS(Realm realm, Class<SignoPracticado> signo) {
            RealmResults<SignoPracticado> results = realm.where(signo).findAll();

            if (results.size() > 0) {
                Number maxId = results.max("id");
                return new AtomicInteger(maxId != null ? maxId.intValue() : 0);
            } else {
                return new AtomicInteger(0);
            }
        }


        private <T extends RealmObject> AtomicInteger getIdByTable(Realm realm, Class<T> anyClass){
        /*
        realm.beginTransaction();
        realm.deleteAll();
        realm.commitTransaction();*/



        RealmResults<T> results = realm.where(anyClass).findAll();

        if (results.size()>0 ){
            return new AtomicInteger(results.max("id").intValue());
        }else{
            realm.beginTransaction();
            Categoria ciudad = new Categoria("Ciudad", R.drawable.ic_ciudad,0);
            realm.copyToRealm(ciudad);
            Categoria colegio = new Categoria("Colegio", R.drawable.ic_colegio,0);
            realm.copyToRealm(colegio);
            Categoria comidasYBebidas = new Categoria("Comida y bebida", R.drawable.comidaybebida,0);
            realm.copyToRealm(comidasYBebidas);
            Categoria cuerpo = new Categoria("Cuerpo", R.drawable.ic_cuerpo,0);
            realm.copyToRealm(cuerpo);
            Categoria familia = new Categoria("Familia", R.drawable.ic_familia,0);
            realm.copyToRealm(familia);
            Categoria naturaleza = new Categoria("Naturaleza", R.drawable.ic_naturaleza,0);
            realm.copyToRealm(naturaleza);
            Categoria ropa = new Categoria("Ropa", R.drawable.ic_ropa,0);
            realm.copyToRealm(ropa);
            Categoria saludosPreguntas = new Categoria("Saludos y Preguntas", R.drawable.ic_preguntas,0);
            realm.copyToRealm(saludosPreguntas);
            Categoria adjetivosAdverbiosVerbos = new Categoria("Adjetivos, Advervios y Verbos", R.drawable.ic_adv,0);
            realm.copyToRealm(adjetivosAdverbiosVerbos);
            Categoria calendario = new Categoria("Calendario", R.drawable.ic_calendario,0);
            realm.copyToRealm(calendario);
            Categoria casa = new Categoria("Casa", R.drawable.casa,0);
            realm.copyToRealm(casa);

            Signo ciudad1 = new Signo("Acera", R.drawable.ciudad_acera, ciudad.getId());
            realm.copyToRealm(ciudad1);
            Signo ciudad2 = new Signo("Ambulancia", R.drawable.ciudad_ambulancia, ciudad.getId());
            realm.copyToRealm(ciudad2);
            Signo ciudad3 = new Signo("Autobus", R.drawable.ciudad_autobus, ciudad.getId());
            realm.copyToRealm(ciudad3);
            Signo ciudad4 = new Signo("Biblioteca", R.drawable.ciudad_biblioteca, ciudad.getId());
            realm.copyToRealm(ciudad4);
            Signo ciudad5 = new Signo("Banco Dinero", R.drawable.ciudad_banco_dinero, ciudad.getId());
            realm.copyToRealm(ciudad5);
            Signo ciudad6 = new Signo("Banco Sentar", R.drawable.ciudad_banco_sentar, ciudad.getId());
            realm.copyToRealm(ciudad6);
            Signo ciudad7 = new Signo("Bicicleta", R.drawable.ciudad_bicicleta, ciudad.getId());
            realm.copyToRealm(ciudad7);
            Signo ciudad8 = new Signo("Bombero", R.drawable.ciudad_bombero, ciudad.getId());
            realm.copyToRealm(ciudad8);
            Signo ciudad9 = new Signo("Buzon", R.drawable.ciudad_buzon, ciudad.getId());
            realm.copyToRealm(ciudad9);
            Signo ciudad10 = new Signo("Calle", R.drawable.ciudad_calle, ciudad.getId());
            realm.copyToRealm(ciudad10);
            Signo ciudad11 = new Signo("Camion", R.drawable.ciudad_camion, ciudad.getId());
            realm.copyToRealm(ciudad11);
            Signo ciudad12 = new Signo("Cine", R.drawable.ciudad_cine, ciudad.getId());
            realm.copyToRealm(ciudad12);
            Signo ciudad13 = new Signo("Ciudad", R.drawable.ciudad_ciudad, ciudad.getId());
            realm.copyToRealm(ciudad13);
            Signo ciudad14 = new Signo("Ciudad Barca", R.drawable.ciudad_ciudad_barca, ciudad.getId());
            realm.copyToRealm(ciudad14);
            Signo ciudad15 = new Signo("Coche", R.drawable.ciudad_coche, ciudad.getId());
            realm.copyToRealm(ciudad15);
            Signo ciudad16 = new Signo("Colegio", R.drawable.ciudad_colegio, ciudad.getId());
            realm.copyToRealm(ciudad16);
            Signo ciudad17 = new Signo("Columpio", R.drawable.ciudad_columpio, ciudad.getId());
            realm.copyToRealm(ciudad17);
            Signo ciudad18 = new Signo("Farola", R.drawable.ciudad_farola, ciudad.getId());
            realm.copyToRealm(ciudad18);
            Signo ciudad19 = new Signo("Fuente", R.drawable.ciudad_fuente, ciudad.getId());
            realm.copyToRealm(ciudad19);
            Signo ciudad20 = new Signo("Hospital", R.drawable.ciudad_hospital, ciudad.getId());
            realm.copyToRealm(ciudad20);
            Signo ciudad21 = new Signo("Libreria", R.drawable.ciudad_libreria, ciudad.getId());
            realm.copyToRealm(ciudad21);
            Signo ciudad22 = new Signo("Luz", R.drawable.ciudad_luz, ciudad.getId());
            realm.copyToRealm(ciudad22);
            Signo ciudad23 = new Signo("Medico", R.drawable.ciudad_medico, ciudad.getId());
            realm.copyToRealm(ciudad23);
            Signo ciudad24 = new Signo("Moto", R.drawable.ciudad_moto, ciudad.getId());
            realm.copyToRealm(ciudad24);
            Signo ciudad25 = new Signo("Museo", R.drawable.ciudad_museo, ciudad.getId());
            realm.copyToRealm(ciudad25);
            Signo ciudad26 = new Signo("Paso de Cebra", R.drawable.ciudad_paso_de_cebra, ciudad.getId());
            realm.copyToRealm(ciudad26);
            Signo ciudad27 = new Signo("Pasteleria", R.drawable.ciudad_pasteleria, ciudad.getId());
            realm.copyToRealm(ciudad27);
            Signo ciudad28 = new Signo("Pastelero", R.drawable.ciudad_pastelero, ciudad.getId());
            realm.copyToRealm(ciudad28);
            Signo ciudad29 = new Signo("Pescador", R.drawable.ciudad_pescador, ciudad.getId());
            realm.copyToRealm(ciudad29);
            Signo ciudad30 = new Signo("Plaza", R.drawable.ciudad_plaza, ciudad.getId());
            realm.copyToRealm(ciudad30);
            Signo ciudad31 = new Signo("Policia", R.drawable.ciudad_policia, ciudad.getId());
            realm.copyToRealm(ciudad31);
            Signo ciudad32 = new Signo("Profesiones", R.drawable.ciudad_profesiones, ciudad.getId());
            realm.copyToRealm(ciudad32);
            Signo ciudad33 = new Signo("Profesor", R.drawable.ciudad_profesor, ciudad.getId());
            realm.copyToRealm(ciudad33);
            Signo ciudad34 = new Signo("Puente", R.drawable.ciudad_puente, ciudad.getId());
            realm.copyToRealm(ciudad34);
            Signo ciudad35 = new Signo("Quiosco", R.drawable.ciudad_quiosco, ciudad.getId());
            realm.copyToRealm(ciudad35);
            Signo ciudad36 = new Signo("Semaforo", R.drawable.ciudad_semaforo, ciudad.getId());
            realm.copyToRealm(ciudad36);
            Signo ciudad37 = new Signo("Supermercado", R.drawable.ciudad_supermercado, ciudad.getId());
            realm.copyToRealm(ciudad37);
            Signo ciudad38 = new Signo("Teatro", R.drawable.ciudad_teatro, ciudad.getId());
            realm.copyToRealm(ciudad38);
            Signo ciudad39 = new Signo("Tienda", R.drawable.ciudad_tienda, ciudad.getId());
            realm.copyToRealm(ciudad39);
            Signo ciudad40 = new Signo("Tobogan", R.drawable.ciudad_tobogan, ciudad.getId());
            realm.copyToRealm(ciudad40);
            Signo ciudad41 = new Signo("Transporte", R.drawable.ciudad_transporte, ciudad.getId());
            realm.copyToRealm(ciudad41);
            Signo ciudad42 = new Signo("Vehiculo", R.drawable.ciudad_vehiculo, ciudad.getId());
            realm.copyToRealm(ciudad42);
            Signo ciudad43 = new Signo("Zapateria", R.drawable.ciudad_zapateria, ciudad.getId());
            realm.copyToRealm(ciudad43);
            Signo ciudad44 = new Signo("Ciudad", R.drawable.ciudad_ciudad, ciudad.getId());
            realm.copyToRealm(ciudad44);

            Signo adjetivosAdverbiosVerbos1 = new Signo("abajo", R.drawable.aaverbos_abajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos1);
            Signo adjetivosAdverbiosVerbos2 = new Signo("abrazar", R.drawable.aaverbos_abrazar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos2);
            Signo adjetivosAdverbiosVerbos3 = new Signo("aburrido", R.drawable.aaverbos_aburrido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos3);
            Signo adjetivosAdverbiosVerbos4 = new Signo("acido", R.drawable.aaverbos_acido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos4);
            Signo adjetivosAdverbiosVerbos5 = new Signo("adjetivos", R.drawable.aaverbos_adjetivos, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos5);
            Signo adjetivosAdverbiosVerbos6 = new Signo("adverbio", R.drawable.aaverbos_adverbio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos6);
            Signo adjetivosAdverbiosVerbos7 = new Signo("agradable", R.drawable.aaverbos_agradable, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos7);
            Signo adjetivosAdverbiosVerbos8 = new Signo("alegre", R.drawable.aaverbos_alegre, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos8);
            Signo adjetivosAdverbiosVerbos9 = new Signo("alto", R.drawable.aaverbos_alto, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos9);
            Signo adjetivosAdverbiosVerbos10 = new Signo("amar", R.drawable.aaverbos_amar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos10);
            Signo adjetivosAdverbiosVerbos11 = new Signo("amargo", R.drawable.aaverbos_amargo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos11);
            Signo adjetivosAdverbiosVerbos12 = new Signo("andar", R.drawable.aaverbos_andar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos12);
            Signo adjetivosAdverbiosVerbos13 = new Signo("aprender", R.drawable.aaverbos_aprender, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos13);
            Signo adjetivosAdverbiosVerbos14 = new Signo("arriba", R.drawable.aaverbos_arriba, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos14);
            Signo adjetivosAdverbiosVerbos15 = new Signo("ayudar", R.drawable.aaverbos_ayudar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos15);
            Signo adjetivosAdverbiosVerbos16 = new Signo("bajo", R.drawable.aaverbos_bajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos16);
            Signo adjetivosAdverbiosVerbos17 = new Signo("beber", R.drawable.aaverbos_beber, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos17);
            Signo adjetivosAdverbiosVerbos18 = new Signo("besar", R.drawable.aaverbos_besar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos18);
            Signo adjetivosAdverbiosVerbos19 = new Signo("bien", R.drawable.aaverbos_bien, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos19);
            Signo adjetivosAdverbiosVerbos20 = new Signo("blando", R.drawable.aaverbos_blando, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos20);
            Signo adjetivosAdverbiosVerbos21 = new Signo("bueno", R.drawable.aaverbos_bueno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos21);
            Signo adjetivosAdverbiosVerbos22 = new Signo("caliente", R.drawable.aaverbos_caliente, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos22);
            Signo adjetivosAdverbiosVerbos23 = new Signo("castano", R.drawable.aaverbos_castano, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos23);
            Signo adjetivosAdverbiosVerbos24 = new Signo("cerca", R.drawable.aaverbos_cerca, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos24);
            Signo adjetivosAdverbiosVerbos25 = new Signo("claro", R.drawable.aaverbos_claro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos25);
            Signo adjetivosAdverbiosVerbos26 = new Signo("comer", R.drawable.aaverbos_comer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos26);
            Signo adjetivosAdverbiosVerbos27 = new Signo("comprar", R.drawable.aaverbos_comprar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos27);
            Signo adjetivosAdverbiosVerbos28 = new Signo("conocer", R.drawable.aaverbos_conocer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos28);
            Signo adjetivosAdverbiosVerbos29 = new Signo("contar", R.drawable.aaverbos_contar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos29);
            Signo adjetivosAdverbiosVerbos30 = new Signo("contento", R.drawable.aaverbos_contento, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos30);
            Signo adjetivosAdverbiosVerbos31 = new Signo("correr", R.drawable.aaverbos_correr, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos31);
            Signo adjetivosAdverbiosVerbos32 = new Signo("cortar", R.drawable.aaverbos_cortar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos32);
            Signo adjetivosAdverbiosVerbos33 = new Signo("crecer-planta", R.drawable.aaverbos_crecer_planta, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos33);
            Signo adjetivosAdverbiosVerbos34 = new Signo("crecer", R.drawable.aaverbos_crecer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos34);
            Signo adjetivosAdverbiosVerbos35 = new Signo("debajo", R.drawable.aaverbos_debajo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos35);
            Signo adjetivosAdverbiosVerbos36 = new Signo("delante", R.drawable.aaverbos_delante, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos36);
            Signo adjetivosAdverbiosVerbos37 = new Signo("delgado", R.drawable.aaverbos_delgado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos37);
            Signo adjetivosAdverbiosVerbos38 = new Signo("dentro", R.drawable.aaverbos_dentro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos38);
            Signo adjetivosAdverbiosVerbos39 = new Signo("derecha", R.drawable.aaverbos_derecha, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos39);
            Signo adjetivosAdverbiosVerbos40 = new Signo("desagradable", R.drawable.aaverbos_desagradable, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos40);
            Signo adjetivosAdverbiosVerbos41 = new Signo("descansar", R.drawable.aaverbos_descansar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos41);
            Signo adjetivosAdverbiosVerbos42 = new Signo("detras", R.drawable.aaverbos_detras, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos42);
            Signo adjetivosAdverbiosVerbos43 = new Signo("diferente", R.drawable.aaverbos_diferente, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos43);
            Signo adjetivosAdverbiosVerbos44 = new Signo("divertido", R.drawable.aaverbos_divertido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos44);
            Signo adjetivosAdverbiosVerbos45 = new Signo("dormir", R.drawable.aaverbos_dormir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos45);
            Signo adjetivosAdverbiosVerbos46 = new Signo("ducharse", R.drawable.aaverbos_ducharse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos46);
            Signo adjetivosAdverbiosVerbos47 = new Signo("dulce (1)", R.drawable.aaverbos_dulce__1_, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos47);
            Signo adjetivosAdverbiosVerbos48 = new Signo("dulce", R.drawable.aaverbos_dulce, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos48);
            Signo adjetivosAdverbiosVerbos49 = new Signo("duro", R.drawable.aaverbos_duro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos49);
            Signo adjetivosAdverbiosVerbos50 = new Signo("encima", R.drawable.aaverbos_encima, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos50);
            Signo adjetivosAdverbiosVerbos51 = new Signo("enfadado", R.drawable.aaverbos_enfadado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos51);
            Signo adjetivosAdverbiosVerbos52 = new Signo("enfermo", R.drawable.aaverbos_enfermo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos52);
            Signo adjetivosAdverbiosVerbos53 = new Signo("entender", R.drawable.aaverbos_entender, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos53);
            Signo adjetivosAdverbiosVerbos54 = new Signo("escribir", R.drawable.aaverbos_escribir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos54);
            Signo adjetivosAdverbiosVerbos55 = new Signo("esperar", R.drawable.aaverbos_esperar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos55);
            Signo adjetivosAdverbiosVerbos56 = new Signo("explicar", R.drawable.aaverbos_explicar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos56);
            Signo adjetivosAdverbiosVerbos57 = new Signo("feo", R.drawable.aaverbos_feo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos57);
            Signo adjetivosAdverbiosVerbos58 = new Signo("frio", R.drawable.aaverbos_frio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos58);
            Signo adjetivosAdverbiosVerbos59 = new Signo("fuera", R.drawable.aaverbos_fuera, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos59);
            Signo adjetivosAdverbiosVerbos60 = new Signo("gordo", R.drawable.aaverbos_gordo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos60);
            Signo adjetivosAdverbiosVerbos61 = new Signo("gritar", R.drawable.aaverbos_gritar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos61);
            Signo adjetivosAdverbiosVerbos62 = new Signo("guapo", R.drawable.aaverbos_guapo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos62);
            Signo adjetivosAdverbiosVerbos63 = new Signo("gustar", R.drawable.aaverbos_gustar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos63);
            /*Signo adjetivosAdverbiosVerbos64 = new Signo("hablar-lse", R.drawable.aaverbos_hablar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos64);*/
            Signo adjetivosAdverbiosVerbos65 = new Signo("hablar-oral", R.drawable.aaverbos_hablar_oral, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos65);
            Signo adjetivosAdverbiosVerbos66 = new Signo("igual", R.drawable.aaverbos_igual, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos66);
            Signo adjetivosAdverbiosVerbos67 = new Signo("izquierda", R.drawable.aaverbos_izquierda, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos67);
            Signo adjetivosAdverbiosVerbos68 = new Signo("jugar", R.drawable.aaverbos_jugar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos68);
            Signo adjetivosAdverbiosVerbos69 = new Signo("lavar-la-cabeza", R.drawable.aaverbos_lavar_la_cabeza, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos69);
            Signo adjetivosAdverbiosVerbos70 = new Signo("lavar-la-ropa", R.drawable.aaverbos_lavar_la_ropa, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos70);
            Signo adjetivosAdverbiosVerbos71 = new Signo("lavar-los-dientes", R.drawable.aaverbos_lavar_los_dientes, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos71);
            Signo adjetivosAdverbiosVerbos72 = new Signo("leer", R.drawable.aaverbos_leer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos72);
            Signo adjetivosAdverbiosVerbos73 = new Signo("lejos", R.drawable.aaverbos_lejos, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos73);
            Signo adjetivosAdverbiosVerbos74 = new Signo("lento", R.drawable.aaverbos_lento, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos74);
            Signo adjetivosAdverbiosVerbos75 = new Signo("levantarse", R.drawable.aaverbos_levantarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos75);
            Signo adjetivosAdverbiosVerbos76 = new Signo("limpio", R.drawable.aaverbos_limpio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos76);
            Signo adjetivosAdverbiosVerbos77 = new Signo("lleno", R.drawable.aaverbos_lleno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos77);
            Signo adjetivosAdverbiosVerbos78 = new Signo("llorar", R.drawable.aaverbos_llorar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos78);
            Signo adjetivosAdverbiosVerbos79 = new Signo("mal", R.drawable.aaverbos_mal, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos79);
            Signo adjetivosAdverbiosVerbos80 = new Signo("malo", R.drawable.aaverbos_malo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos80);
            Signo adjetivosAdverbiosVerbos81 = new Signo("montar", R.drawable.aaverbos_montar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos81);
            Signo adjetivosAdverbiosVerbos82 = new Signo("moreno", R.drawable.aaverbos_moreno, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos82);
            Signo adjetivosAdverbiosVerbos83 = new Signo("mucho", R.drawable.aaverbos_mucho, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos83);
            Signo adjetivosAdverbiosVerbos84 = new Signo("nacer", R.drawable.aaverbos_nacer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos84);
            Signo adjetivosAdverbiosVerbos85 = new Signo("no-conocer", R.drawable.aaverbos_no_conocer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos85);
            Signo adjetivosAdverbiosVerbos86 = new Signo("no-gustar", R.drawable.aaverbos_no_gustar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos86);
            Signo adjetivosAdverbiosVerbos87 = new Signo("no-tener", R.drawable.aaverbos_no_tener, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos87);
            Signo adjetivosAdverbiosVerbos88 = new Signo("oir", R.drawable.aaverbos_oir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos88);
            Signo adjetivosAdverbiosVerbos89 = new Signo("oler", R.drawable.aaverbos_oler, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos89);
            Signo adjetivosAdverbiosVerbos90 = new Signo("oscuro", R.drawable.aaverbos_oscuro, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos90);
            Signo adjetivosAdverbiosVerbos91 = new Signo("pasear", R.drawable.aaverbos_pasear, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos91);
            Signo adjetivosAdverbiosVerbos92 = new Signo("patinar", R.drawable.aaverbos_patinar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos92);
            Signo adjetivosAdverbiosVerbos93 = new Signo("pegar", R.drawable.aaverbos_pegar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos93);
            Signo adjetivosAdverbiosVerbos94 = new Signo("peinarse", R.drawable.aaverbos_peinarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos94);
            Signo adjetivosAdverbiosVerbos95 = new Signo("pelirrojo", R.drawable.aaverbos_pelirrojo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos95);
            Signo adjetivosAdverbiosVerbos96 = new Signo("poco", R.drawable.aaverbos_aaverbos_poco, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos96);
            Signo adjetivosAdverbiosVerbos97 = new Signo("ponerse", R.drawable.aaverbos_ponerse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos97);
            Signo adjetivosAdverbiosVerbos98 = new Signo("primer", R.drawable.aaverbos_primer, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos98);
            Signo adjetivosAdverbiosVerbos99 = new Signo("quitarse", R.drawable.aaverbos_quitarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos99);
            Signo adjetivosAdverbiosVerbos100 = new Signo("rapido", R.drawable.aaverbos_rapido, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos100);
            Signo adjetivosAdverbiosVerbos101 = new Signo("regalar", R.drawable.aaverbos_regalar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos101);
            Signo adjetivosAdverbiosVerbos102 = new Signo("reir", R.drawable.aaverbos_reir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos102);
            Signo adjetivosAdverbiosVerbos103 = new Signo("rubio", R.drawable.aaverbos_rubio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos103);
            Signo adjetivosAdverbiosVerbos104 = new Signo("saborear", R.drawable.aaverbos_saborear, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos104);
            Signo adjetivosAdverbiosVerbos105 = new Signo("salado", R.drawable.aaverbos_salado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos105);
            Signo adjetivosAdverbiosVerbos106 = new Signo("saltar", R.drawable.aaverbos_saltar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos106);
            Signo adjetivosAdverbiosVerbos107 = new Signo("sano", R.drawable.aaverbos_sano, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos107);
            Signo adjetivosAdverbiosVerbos108 = new Signo("sentarse", R.drawable.aaverbos_sentarse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos108);
            Signo adjetivosAdverbiosVerbos109 = new Signo("sucio", R.drawable.aaverbos_sucio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos109);
            Signo adjetivosAdverbiosVerbos110 = new Signo("templado", R.drawable.aaverbos_templado, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos110);
            Signo adjetivosAdverbiosVerbos111 = new Signo("tener", R.drawable.aaverbos_tener, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos111);
            Signo adjetivosAdverbiosVerbos112 = new Signo("tocar", R.drawable.aaverbos_tocar, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos112);
            Signo adjetivosAdverbiosVerbos113 = new Signo("triste", R.drawable.aaverbos_triste, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos113);
            Signo adjetivosAdverbiosVerbos114 = new Signo("ultimo", R.drawable.aaverbos_ultimo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos114);
            Signo adjetivosAdverbiosVerbos115 = new Signo("vacio", R.drawable.aaverbos_vacio, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos115);
            Signo adjetivosAdverbiosVerbos116 = new Signo("vamos-a", R.drawable.aaverbos_vamos_a, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos116);
            Signo adjetivosAdverbiosVerbos117 = new Signo("ver", R.drawable.aaverbos_ver, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos117);
            Signo adjetivosAdverbiosVerbos118 = new Signo("verbo", R.drawable.aaverbos_verbo, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos118);
            Signo adjetivosAdverbiosVerbos119 = new Signo("vestirse", R.drawable.aaverbos_vestirse, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos119);
            Signo adjetivosAdverbiosVerbos120 = new Signo("vivir", R.drawable.aaverbos_vivir, adjetivosAdverbiosVerbos.getId());
            realm.copyToRealm(adjetivosAdverbiosVerbos120);

            Signo calendario1 = new Signo("ayer", R.drawable.calendario_ayer, calendario.getId());
            realm.copyToRealm(calendario1);
            Signo calendario2 = new Signo("calendario", R.drawable.calendario_calendario, calendario.getId());
            realm.copyToRealm(calendario2);
            Signo calendario3 = new Signo("cumpleanos", R.drawable.calendario_cumpleanos, calendario.getId());
            realm.copyToRealm(calendario3);
            Signo calendario4 = new Signo("dia-de-la-semana", R.drawable.calendario_dia_de_la_semana, calendario.getId());
            realm.copyToRealm(calendario4);
            Signo calendario5 = new Signo("dia-manana", R.drawable.calendario_dia_manana, calendario.getId());
            realm.copyToRealm(calendario5);
            Signo calendario6 = new Signo("diciembre", R.drawable.calendario_diciembre, calendario.getId());
            realm.copyToRealm(calendario6);
            Signo calendario7 = new Signo("domingo", R.drawable.calendario_domingo, calendario.getId());
            realm.copyToRealm(calendario7);
            Signo calendario8 = new Signo("en-punto", R.drawable.calendario_en_punto, calendario.getId());
            realm.copyToRealm(calendario8);
            Signo calendario9 = new Signo("estaciones", R.drawable.calendario_estaciones, calendario.getId());
            realm.copyToRealm(calendario9);
            Signo calendario10 = new Signo("fiesta", R.drawable.calendario_fiesta, calendario.getId());
            realm.copyToRealm(calendario10);
            Signo calendario11 = new Signo("fin-de-semana", R.drawable.calendario_fin_de_semana, calendario.getId());
            realm.copyToRealm(calendario11);
            Signo calendario12 = new Signo("hora-interrogativa", R.drawable.calendario_hora_interrogativa, calendario.getId());
            realm.copyToRealm(calendario12);
            Signo calendario13 = new Signo("hoy", R.drawable.calendario_hoy, calendario.getId());
            realm.copyToRealm(calendario13);
            Signo calendario14 = new Signo("invierno", R.drawable.calendario_invierno, calendario.getId());
            realm.copyToRealm(calendario14);
            Signo calendario15 = new Signo("jueves", R.drawable.calendario_jueves, calendario.getId());
            realm.copyToRealm(calendario15);
            Signo calendario16 = new Signo("junio", R.drawable.calendario_junio, calendario.getId());
            realm.copyToRealm(calendario16);
            Signo calendario17 = new Signo("la-hora-de", R.drawable.calendario_la_hora_de, calendario.getId());
            realm.copyToRealm(calendario17);
            Signo calendario18 = new Signo("lunes", R.drawable.calendario_lunes, calendario.getId());
            realm.copyToRealm(calendario18);
            Signo calendario19 = new Signo("manana", R.drawable.calendario_manana, calendario.getId());
            realm.copyToRealm(calendario19);
            Signo calendario20 = new Signo("martes", R.drawable.calendario_martes, calendario.getId());
            realm.copyToRealm(calendario20);
            Signo calendario21 = new Signo("mayo", R.drawable.calendario_mayo, calendario.getId());
            realm.copyToRealm(calendario21);
            Signo calendario22 = new Signo("menos-cuarto", R.drawable.calendario_menos_cuarto, calendario.getId());
            realm.copyToRealm(calendario22);
            Signo calendario23 = new Signo("mes", R.drawable.calendario_mes, calendario.getId());
            realm.copyToRealm(calendario23);
            Signo calendario24 = new Signo("meses-del-ano", R.drawable.calendario_meses_del_ano, calendario.getId());
            realm.copyToRealm(calendario24);
            Signo calendario25 = new Signo("miercoles", R.drawable.calendario_miercoles, calendario.getId());
            realm.copyToRealm(calendario25);
            Signo calendario26 = new Signo("navidad", R.drawable.calendario_navidad, calendario.getId());
            realm.copyToRealm(calendario26);
            Signo calendario27 = new Signo("noviembre", R.drawable.calendario_noviembre, calendario.getId());
            realm.copyToRealm(calendario27);
            Signo calendario28 = new Signo("octubre", R.drawable.calendario_octubre, calendario.getId());
            realm.copyToRealm(calendario28);
            Signo calendario29 = new Signo("otono", R.drawable.calendario_otono, calendario.getId());
            realm.copyToRealm(calendario29);
            Signo calendario30 = new Signo("papa-noel", R.drawable.calendario_papa_noel, calendario.getId());
            realm.copyToRealm(calendario30);
            Signo calendario31 = new Signo("por-la-manana", R.drawable.calendario_por_la_manana, calendario.getId());
            realm.copyToRealm(calendario31);
            Signo calendario32 = new Signo("por-la-noche", R.drawable.calendario_por_la_noche, calendario.getId());
            realm.copyToRealm(calendario32);
            Signo calendario33 = new Signo("por-la-tarde", R.drawable.calendario_por_la_tarde, calendario.getId());
            realm.copyToRealm(calendario33);
            Signo calendario34 = new Signo("primavera", R.drawable.calendario_primavera, calendario.getId());
            realm.copyToRealm(calendario34);
            Signo calendario35 = new Signo("reyes-magos", R.drawable.calendario_reyes_magos, calendario.getId());
            realm.copyToRealm(calendario35);
            Signo calendario36 = new Signo("sabado", R.drawable.calendario_sabado, calendario.getId());
            realm.copyToRealm(calendario36);
            Signo calendario37 = new Signo("semana", R.drawable.calendario_semana, calendario.getId());
            realm.copyToRealm(calendario37);
            Signo calendario38 = new Signo("septiembre", R.drawable.calendario_septiembre, calendario.getId());
            realm.copyToRealm(calendario38);
            Signo calendario39 = new Signo("tiempo", R.drawable.calendario_tiempo, calendario.getId());
            realm.copyToRealm(calendario39);
            Signo calendario40 = new Signo("verano", R.drawable.calendario_verano, calendario.getId());
            realm.copyToRealm(calendario40);
            Signo calendario41 = new Signo("viernes", R.drawable.calendario_viernes, calendario.getId());
            realm.copyToRealm(calendario41);
            Signo calendario42 = new Signo("y-cuarto", R.drawable.calendario_y_cuarto, calendario.getId());
            realm.copyToRealm(calendario42);
            Signo calendario43 = new Signo("y-media", R.drawable.calendario_y_media, calendario.getId());
            realm.copyToRealm(calendario43);

            Signo casa1 = new Signo("alfombra", R.drawable.casa_alfombra, casa.getId());
            realm.copyToRealm(casa1);
            Signo casa2 = new Signo("armario", R.drawable.casa_armario, casa.getId());
            realm.copyToRealm(casa2);
            Signo casa3 = new Signo("banera", R.drawable.casa_banera, casa.getId());
            realm.copyToRealm(casa3);
            Signo casa4 = new Signo("bano", R.drawable.casa_bano, casa.getId());
            realm.copyToRealm(casa4);
            Signo casa5 = new Signo("cacerola", R.drawable.casa_cacerola, casa.getId());
            realm.copyToRealm(casa5);
            Signo casa6 = new Signo("cama", R.drawable.casa_cama, casa.getId());
            realm.copyToRealm(casa6);
            Signo casa7 = new Signo("casa", R.drawable.casa_casa, casa.getId());
            realm.copyToRealm(casa7);
            Signo casa8 = new Signo("cepillo", R.drawable.casa_cepillo, casa.getId());
            realm.copyToRealm(casa8);
            Signo casa9 = new Signo("champu", R.drawable.casa_champu, casa.getId());
            realm.copyToRealm(casa9);
            Signo casa10 = new Signo("cocina", R.drawable.casa_cocina, casa.getId());
            realm.copyToRealm(casa10);
            Signo casa11 = new Signo("colonia", R.drawable.casa_colonia, casa.getId());
            realm.copyToRealm(casa11);
            Signo casa12 = new Signo("cristal", R.drawable.casa_cristal, casa.getId());
            realm.copyToRealm(casa12);
            Signo casa13 = new Signo("cuchara", R.drawable.casa_cuchara, casa.getId());
            realm.copyToRealm(casa13);
            Signo casa14 = new Signo("cuchillo", R.drawable.casa_cuchillo, casa.getId());
            realm.copyToRealm(casa14);
            Signo casa15 = new Signo("despertador", R.drawable.casa_despertador, casa.getId());
            realm.copyToRealm(casa15);
            Signo casa16 = new Signo("dormitorio", R.drawable.casa_dormitorio, casa.getId());
            realm.copyToRealm(casa16);
            Signo casa17 = new Signo("espejo", R.drawable.casa_espejo, casa.getId());
            realm.copyToRealm(casa17);
            Signo casa18 = new Signo("esponja", R.drawable.casa_esponja, casa.getId());
            realm.copyToRealm(casa18);
            Signo casa19 = new Signo("fax", R.drawable.casa_fax, casa.getId());
            realm.copyToRealm(casa19);
            Signo casa20 = new Signo("jabon", R.drawable.casa_jabon, casa.getId());
            realm.copyToRealm(casa20);
            Signo casa21 = new Signo("jarra", R.drawable.casa_jarra, casa.getId());
            realm.copyToRealm(casa21);
            Signo casa22 = new Signo("lampara", R.drawable.casa_lampara, casa.getId());
            realm.copyToRealm(casa22);
            Signo casa23 = new Signo("lavabo", R.drawable.casa_lavabo, casa.getId());
            realm.copyToRealm(casa23);
            Signo casa24 = new Signo("lavadora", R.drawable.casa_lavadora, casa.getId());
            realm.copyToRealm(casa24);
            Signo casa25 = new Signo("maceta", R.drawable.casa_maceta, casa.getId());
            realm.copyToRealm(casa25);
            Signo casa26 = new Signo("manta", R.drawable.casa_manta, casa.getId());
            realm.copyToRealm(casa26);
            Signo casa27 = new Signo("maquina", R.drawable.casa_maquina, casa.getId());
            realm.copyToRealm(casa27);
            Signo casa28 = new Signo("mesilla", R.drawable.casa_mesilla, casa.getId());
            realm.copyToRealm(casa28);
            Signo casa29 = new Signo("mueble", R.drawable.casa_mueble, casa.getId());
            realm.copyToRealm(casa29);
            Signo casa30 = new Signo("muneco", R.drawable.casa_muneco, casa.getId());
            realm.copyToRealm(casa30);
            Signo casa31 = new Signo("nevera", R.drawable.casa_nevera, casa.getId());
            realm.copyToRealm(casa31);
            Signo casa32 = new Signo("objeto", R.drawable.casa_objeto, casa.getId());
            realm.copyToRealm(casa32);
            Signo casa33 = new Signo("objetos", R.drawable.casa_objetos, casa.getId());
            realm.copyToRealm(casa33);
            Signo casa34 = new Signo("ordenador", R.drawable.casa_ordenador, casa.getId());
            realm.copyToRealm(casa34);
            Signo casa35 = new Signo("papel", R.drawable.casa_papel, casa.getId());
            realm.copyToRealm(casa35);
            Signo casa36 = new Signo("pasta-de-dientes", R.drawable.casa_pasta_de_dientes, casa.getId());
            realm.copyToRealm(casa36);
            Signo casa37 = new Signo("peine", R.drawable.casa_peine, casa.getId());
            realm.copyToRealm(casa37);
            Signo casa38 = new Signo("pelota", R.drawable.casa_pelota, casa.getId());
            realm.copyToRealm(casa38);
            Signo casa39 = new Signo("plancha", R.drawable.casa_plancha, casa.getId());
            realm.copyToRealm(casa39);
            Signo casa40 = new Signo("plato", R.drawable.casa_plato, casa.getId());
            realm.copyToRealm(casa40);
            Signo casa41 = new Signo("puerta", R.drawable.casa_puerta, casa.getId());
            realm.copyToRealm(casa41);
            Signo casa42 = new Signo("sabana", R.drawable.casa_sabana, casa.getId());
            realm.copyToRealm(casa42);
            Signo casa43 = new Signo("salon", R.drawable.casa_salon, casa.getId());
            realm.copyToRealm(casa43);
            Signo casa44 = new Signo("sarten", R.drawable.casa_sarten, casa.getId());
            realm.copyToRealm(casa44);
            Signo casa45 = new Signo("servilleta", R.drawable.casa_servilleta, casa.getId());
            realm.copyToRealm(casa45);
            Signo casa46 = new Signo("silla", R.drawable.casa_silla, casa.getId());
            realm.copyToRealm(casa46);
            Signo casa47 = new Signo("sofa", R.drawable.casa_sofa, casa.getId());
            realm.copyToRealm(casa47);
            Signo casa48 = new Signo("telefono", R.drawable.casa_telefono, casa.getId());
            realm.copyToRealm(casa48);
            Signo casa49 = new Signo("televisor", R.drawable.casa_televisor, casa.getId());
            realm.copyToRealm(casa49);
            Signo casa50 = new Signo("tenedor", R.drawable.casa_tenedor, casa.getId());
            realm.copyToRealm(casa50);
            Signo casa51 = new Signo("toalla", R.drawable.casa_toalla, casa.getId());
            realm.copyToRealm(casa51);
            Signo casa52 = new Signo("vaso", R.drawable.casa_vaso, casa.getId());
            realm.copyToRealm(casa52);
            Signo casa53 = new Signo("ventana", R.drawable.casa_ventana, casa.getId());
            realm.copyToRealm(casa53);
            Signo casa54 = new Signo("video", R.drawable.casa_video, casa.getId());
            realm.copyToRealm(casa54);

            Signo saludosPreguntas1 = new Signo("adios", R.drawable.saludos_adios, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas1);
            Signo saludosPreguntas2 = new Signo("buenas-noches", R.drawable.saludos_buenas_noches, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas2);
            Signo saludosPreguntas3 = new Signo("buenas-tardes", R.drawable.saludos_buenas_tardes, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas3);
            Signo saludosPreguntas4 = new Signo("buenos-dias", R.drawable.saludos_buenos_dias, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas4);
            Signo saludosPreguntas5 = new Signo("cortesia", R.drawable.saludos_cortesia, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas5);
            Signo saludosPreguntas6 = new Signo("cuidado", R.drawable.saludos_cuidado, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas6);
            Signo saludosPreguntas7 = new Signo("de-nada", R.drawable.saludos_de_nada, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas7);
            Signo saludosPreguntas8 = new Signo("gracias", R.drawable.saludos_gracias, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas8);
            Signo saludosPreguntas9 = new Signo("hola", R.drawable.saludos_hola, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas9);
            Signo saludosPreguntas10 = new Signo("no", R.drawable.saludos_no, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas10);
            Signo saludosPreguntas11 = new Signo("nombre", R.drawable.saludos_nombre, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas11);
            Signo saludosPreguntas12 = new Signo("por-favor", R.drawable.saludos_por_favor, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas12);
            Signo saludosPreguntas13 = new Signo("saludo", R.drawable.saludos_saludo, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas13);
            Signo saludosPreguntas14 = new Signo("si", R.drawable.saludos_si, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas14);
            Signo saludosPreguntas15 = new Signo("signo", R.drawable.saludos_signo, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas15);
            Signo saludosPreguntas16 = new Signo("como-se-dice", R.drawable.saludos_como_se_dice, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas16);
            Signo saludosPreguntas17 = new Signo("como-se-signa", R.drawable.saludos_como_se_signa, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas17);
            Signo saludosPreguntas18 = new Signo("como", R.drawable.saludos_como, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas18);
            Signo saludosPreguntas19 = new Signo("cual", R.drawable.saludos_cual, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas19);
            Signo saludosPreguntas20 = new Signo("cuando-pasado", R.drawable.saludos_cuando_pasado, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas20);
            Signo saludosPreguntas21 = new Signo("cuando-presente-y-futuro", R.drawable.saludos_cuando_presente_y_futuro, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas21);
            Signo saludosPreguntas22 = new Signo("cuanto", R.drawable.saludos_cuanto, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas22);
            Signo saludosPreguntas23 = new Signo("donde", R.drawable.saludos_donde, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas23);
            /*
            Signo saludosPreguntas24 = new Signo("para-que", R.drawable.saludos_para, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas24);
            Signo saludosPreguntas25 = new Signo("por-que", R.drawable.saludos_por, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas25);*/
            Signo saludosPreguntas26 = new Signo("preguntas", R.drawable.saludos_preguntas, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas26);
            Signo saludosPreguntas27 = new Signo("que-dia-es", R.drawable.saludos_que_dia_es, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas27);
            Signo saludosPreguntas28 = new Signo("que-dice", R.drawable.saludos_que_dice, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas28);
            Signo saludosPreguntas29 = new Signo("que-tal", R.drawable.saludos_que, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas29);
            Signo saludosPreguntas30 = new Signo("que", R.drawable.saludos_que, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas30);
            Signo saludosPreguntas31 = new Signo("quien", R.drawable.saludos_quien, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas31);
            Signo saludosPreguntas32 = new Signo("si-o-no", R.drawable.saludos_si_o_no, saludosPreguntas.getId());
            realm.copyToRealm(saludosPreguntas32);

            Signo ropa1 = new Signo("abrigo", R.drawable.ropa_abrigo, ropa.getId());
            realm.copyToRealm(ropa1);
            Signo ropa2 = new Signo("banador-chica", R.drawable.ropa_banador_chica, ropa.getId());
            realm.copyToRealm(ropa2);
            Signo ropa3 = new Signo("banador-chico", R.drawable.ropa_banador_chico, ropa.getId());
            realm.copyToRealm(ropa3);
            Signo ropa4 = new Signo("braga", R.drawable.ropa_braga, ropa.getId());
            realm.copyToRealm(ropa4);
            Signo ropa5 = new Signo("bufanda", R.drawable.ropa_bufanda, ropa.getId());
            realm.copyToRealm(ropa5);
            Signo ropa6 = new Signo("calzoncillo", R.drawable.ropa_calzoncillo, ropa.getId());
            realm.copyToRealm(ropa6);
            Signo ropa7 = new Signo("camisa", R.drawable.ropa_camisa, ropa.getId());
            realm.copyToRealm(ropa7);
            Signo ropa8 = new Signo("chandal", R.drawable.ropa_chandal, ropa.getId());
            realm.copyToRealm(ropa8);
            Signo ropa9 = new Signo("gafas", R.drawable.ropa_gafas, ropa.getId());
            realm.copyToRealm(ropa9);
            Signo ropa10 = new Signo("gorra", R.drawable.ropa_gorra, ropa.getId());
            realm.copyToRealm(ropa10);
            Signo ropa11 = new Signo("jersey", R.drawable.ropa_jersey, ropa.getId());
            realm.copyToRealm(ropa11);
            Signo ropa12 = new Signo("mochila", R.drawable.ropa_mochila, ropa.getId());
            realm.copyToRealm(ropa12);
            Signo ropa13 = new Signo("pantalon", R.drawable.ropa_pantalon, ropa.getId());
            realm.copyToRealm(ropa13);
            Signo ropa14 = new Signo("pijama", R.drawable.ropa_pijama, ropa.getId());
            realm.copyToRealm(ropa14);
            Signo ropa15 = new Signo("reloj", R.drawable.ropa_reloj, ropa.getId());
            realm.copyToRealm(ropa15);
            Signo ropa16 = new Signo("ropa", R.drawable.ropa_ropa, ropa.getId());
            realm.copyToRealm(ropa16);
            Signo ropa17 = new Signo("zapatilla", R.drawable.ropa_zapatilla, ropa.getId());
            realm.copyToRealm(ropa17);
            Signo ropa18 = new Signo("zapato", R.drawable.ropa_zapato, ropa.getId());
            realm.copyToRealm(ropa18);

            Signo naturaleza1 = new Signo("abeja", R.drawable.naturaleza_abeja, naturaleza.getId());
            realm.copyToRealm(naturaleza1);
            Signo naturaleza2 = new Signo("aguila", R.drawable.naturaleza_aguila, naturaleza.getId());
            realm.copyToRealm(naturaleza2);
            Signo naturaleza3 = new Signo("animal", R.drawable.naturaleza_animal, naturaleza.getId());
            realm.copyToRealm(naturaleza3);
            Signo naturaleza4 = new Signo("ballena", R.drawable.naturaleza_ballena, naturaleza.getId());
            realm.copyToRealm(naturaleza4);
            Signo naturaleza5 = new Signo("burro", R.drawable.naturaleza_burro, naturaleza.getId());
            realm.copyToRealm(naturaleza5);
            Signo naturaleza6 = new Signo("caballo", R.drawable.naturaleza_caballo, naturaleza.getId());
            realm.copyToRealm(naturaleza6);
            Signo naturaleza7 = new Signo("cabra", R.drawable.naturaleza_cabra, naturaleza.getId());
            realm.copyToRealm(naturaleza7);
            Signo naturaleza8 = new Signo("camello", R.drawable.naturaleza_camello, naturaleza.getId());
            realm.copyToRealm(naturaleza8);
            Signo naturaleza9 = new Signo("cerdo", R.drawable.naturaleza_cerdo, naturaleza.getId());
            realm.copyToRealm(naturaleza9);
            Signo naturaleza10 = new Signo("cocodrilo", R.drawable.naturaleza_cocodrilo, naturaleza.getId());
            realm.copyToRealm(naturaleza10);
            Signo naturaleza11 = new Signo("conejo", R.drawable.naturaleza_conejo, naturaleza.getId());
            realm.copyToRealm(naturaleza11);
            Signo naturaleza12 = new Signo("delfin", R.drawable.naturaleza_delfin, naturaleza.getId());
            realm.copyToRealm(naturaleza12);
            Signo naturaleza13 = new Signo("elefante", R.drawable.naturaleza_elefante, naturaleza.getId());
            realm.copyToRealm(naturaleza13);
            Signo naturaleza14 = new Signo("foca", R.drawable.naturaleza_foca, naturaleza.getId());
            realm.copyToRealm(naturaleza14);
            Signo naturaleza15 = new Signo("gallina", R.drawable.naturaleza_gallina, naturaleza.getId());
            realm.copyToRealm(naturaleza15);
            Signo naturaleza16 = new Signo("gato", R.drawable.naturaleza_gato, naturaleza.getId());
            realm.copyToRealm(naturaleza16);
            Signo naturaleza17 = new Signo("granja", R.drawable.naturaleza_granja, naturaleza.getId());
            realm.copyToRealm(naturaleza17);
            Signo naturaleza18 = new Signo("jirafa", R.drawable.naturaleza_jirafa, naturaleza.getId());
            realm.copyToRealm(naturaleza18);
            Signo naturaleza19 = new Signo("leon", R.drawable.naturaleza_leon, naturaleza.getId());
            realm.copyToRealm(naturaleza19);
            Signo naturaleza20 = new Signo("loro", R.drawable.naturaleza_loro, naturaleza.getId());
            realm.copyToRealm(naturaleza20);
            Signo naturaleza21 = new Signo("mariposa", R.drawable.naturaleza_mariposa, naturaleza.getId());
            realm.copyToRealm(naturaleza21);
            Signo naturaleza22 = new Signo("mono", R.drawable.naturaleza_mono, naturaleza.getId());
            realm.copyToRealm(naturaleza22);
            Signo naturaleza23 = new Signo("oso", R.drawable.naturaleza_oso, naturaleza.getId());
            realm.copyToRealm(naturaleza23);
            Signo naturaleza24 = new Signo("oveja", R.drawable.naturaleza_oveja, naturaleza.getId());
            realm.copyToRealm(naturaleza24);
            Signo naturaleza25 = new Signo("pajaro", R.drawable.naturaleza_pajaro, naturaleza.getId());
            realm.copyToRealm(naturaleza25);
            Signo naturaleza26 = new Signo("pato", R.drawable.naturaleza_pato, naturaleza.getId());
            realm.copyToRealm(naturaleza26);
            Signo naturaleza27 = new Signo("perro", R.drawable.naturaleza_perro, naturaleza.getId());
            realm.copyToRealm(naturaleza27);
            Signo naturaleza28 = new Signo("tiburon", R.drawable.naturaleza_tiburon, naturaleza.getId());
            realm.copyToRealm(naturaleza28);
            Signo naturaleza29 = new Signo("tigre", R.drawable.naturaleza_tigre, naturaleza.getId());
            realm.copyToRealm(naturaleza29);
            Signo naturaleza30 = new Signo("toro", R.drawable.naturaleza_toro, naturaleza.getId());
            realm.copyToRealm(naturaleza30);
            Signo naturaleza31 = new Signo("tortuga", R.drawable.naturaleza_tortuga, naturaleza.getId());
            realm.copyToRealm(naturaleza31);
            Signo naturaleza32 = new Signo("vaca", R.drawable.naturaleza_vaca, naturaleza.getId());
            realm.copyToRealm(naturaleza32);
            Signo naturaleza33 = new Signo("zoo", R.drawable.naturaleza_zoo, naturaleza.getId());
            realm.copyToRealm(naturaleza33);
            Signo naturaleza34 = new Signo("abeto", R.drawable.naturaleza_abeto, naturaleza.getId());
            realm.copyToRealm(naturaleza34);
            Signo naturaleza35 = new Signo("arbol", R.drawable.naturaleza_arbol, naturaleza.getId());
            realm.copyToRealm(naturaleza35);
            Signo naturaleza36 = new Signo("arco-iris", R.drawable.naturaleza_arco_iris, naturaleza.getId());
            realm.copyToRealm(naturaleza36);
            Signo naturaleza37 = new Signo("arena", R.drawable.naturaleza_arena, naturaleza.getId());
            realm.copyToRealm(naturaleza37);
            Signo naturaleza38 = new Signo("estrella", R.drawable.naturaleza_estrella, naturaleza.getId());
            realm.copyToRealm(naturaleza38);
            Signo naturaleza39 = new Signo("faro", R.drawable.naturaleza_faro, naturaleza.getId());
            realm.copyToRealm(naturaleza39);
            Signo naturaleza40 = new Signo("flor", R.drawable.naturaleza_flor, naturaleza.getId());
            realm.copyToRealm(naturaleza40);
            Signo naturaleza41 = new Signo("flotador", R.drawable.naturaleza_flotador, naturaleza.getId());
            realm.copyToRealm(naturaleza41);
            Signo naturaleza42 = new Signo("fuego", R.drawable.naturaleza_fuego, naturaleza.getId());
            realm.copyToRealm(naturaleza42);
            Signo naturaleza43 = new Signo("hierba", R.drawable.naturaleza_hierba, naturaleza.getId());
            realm.copyToRealm(naturaleza43);
            Signo naturaleza44 = new Signo("hoja", R.drawable.naturaleza_hoja, naturaleza.getId());
            realm.copyToRealm(naturaleza44);
            Signo naturaleza45 = new Signo("lago", R.drawable.naturaleza_lago, naturaleza.getId());
            realm.copyToRealm(naturaleza45);
            Signo naturaleza46 = new Signo("luna", R.drawable.naturaleza_luna, naturaleza.getId());
            realm.copyToRealm(naturaleza46);
            Signo naturaleza47 = new Signo("mar", R.drawable.naturaleza_mar, naturaleza.getId());
            realm.copyToRealm(naturaleza47);
            Signo naturaleza48 = new Signo("margarita", R.drawable.naturaleza_margarita, naturaleza.getId());
            realm.copyToRealm(naturaleza48);
            Signo naturaleza49 = new Signo("montana", R.drawable.naturaleza_montana, naturaleza.getId());
            realm.copyToRealm(naturaleza49);
            Signo naturaleza50 = new Signo("naturaleza", R.drawable.naturaleza_naturaleza, naturaleza.getId());
            realm.copyToRealm(naturaleza50);
            Signo naturaleza51 = new Signo("palmera", R.drawable.naturaleza_palmera, naturaleza.getId());
            realm.copyToRealm(naturaleza51);
            Signo naturaleza52 = new Signo("piedra", R.drawable.naturaleza_piedra, naturaleza.getId());
            realm.copyToRealm(naturaleza52);
            Signo naturaleza53 = new Signo("playa", R.drawable.naturaleza_playa, naturaleza.getId());
            realm.copyToRealm(naturaleza53);
            Signo naturaleza54 = new Signo("pozo", R.drawable.naturaleza_pozo, naturaleza.getId());
            realm.copyToRealm(naturaleza54);
            Signo naturaleza55 = new Signo("rio", R.drawable.naturaleza_rio, naturaleza.getId());
            realm.copyToRealm(naturaleza55);
            Signo naturaleza56 = new Signo("saco-de-dormir", R.drawable.naturaleza_saco_de_dormir, naturaleza.getId());
            realm.copyToRealm(naturaleza56);
            Signo naturaleza57 = new Signo("sombrilla", R.drawable.naturaleza_sombrilla, naturaleza.getId());
            realm.copyToRealm(naturaleza57);
            Signo naturaleza58 = new Signo("tienda-campana", R.drawable.naturaleza_tienda_campana, naturaleza.getId());
            realm.copyToRealm(naturaleza58);
            Signo naturaleza59 = new Signo("calor", R.drawable.naturaleza_calor, naturaleza.getId());
            realm.copyToRealm(naturaleza59);
            Signo naturaleza60 = new Signo("frio", R.drawable.naturaleza_frio, naturaleza.getId());
            realm.copyToRealm(naturaleza60);
            Signo naturaleza61 = new Signo("lluvia", R.drawable.naturaleza_lluvia, naturaleza.getId());
            realm.copyToRealm(naturaleza61);
            Signo naturaleza62 = new Signo("nieve", R.drawable.naturaleza_nieve, naturaleza.getId());
            realm.copyToRealm(naturaleza62);
            Signo naturaleza63 = new Signo("nube", R.drawable.naturaleza_nube, naturaleza.getId());
            realm.copyToRealm(naturaleza63);
            Signo naturaleza64 = new Signo("nublado", R.drawable.naturaleza_nublado, naturaleza.getId());
            realm.copyToRealm(naturaleza64);
            Signo naturaleza65 = new Signo("sol", R.drawable.naturaleza_sol, naturaleza.getId());
            realm.copyToRealm(naturaleza65);
            Signo naturaleza66 = new Signo("tiempo-atmosferico", R.drawable.naturaleza_tiempo_atmosferico, naturaleza.getId());
            realm.copyToRealm(naturaleza66);
            Signo naturaleza67 = new Signo("tormenta", R.drawable.naturaleza_tormenta, naturaleza.getId());
            realm.copyToRealm(naturaleza67);
            Signo naturaleza68 = new Signo("viento", R.drawable.naturaleza_viento, naturaleza.getId());
            realm.copyToRealm(naturaleza68);

            Signo familia1 = new Signo("abuelo", R.drawable.familia_abuelo, familia.getId());
            realm.copyToRealm(familia1);
            Signo familia2 = new Signo("amigo", R.drawable.familia_amigo, familia.getId());
            realm.copyToRealm(familia2);
            Signo familia3 = new Signo("bebe", R.drawable.familia_bebe, familia.getId());
            realm.copyToRealm(familia3);
            Signo familia4 = new Signo("ciego", R.drawable.familia_ciego, familia.getId());
            realm.copyToRealm(familia4);
            Signo familia5 = new Signo("familia", R.drawable.familia_familia, familia.getId());
            realm.copyToRealm(familia5);
            Signo familia6 = new Signo("hermano", R.drawable.familia_hermano, familia.getId());
            realm.copyToRealm(familia6);
            Signo familia7 = new Signo("mama", R.drawable.familia_mama, familia.getId());
            realm.copyToRealm(familia7);
            Signo familia8 = new Signo("nina", R.drawable.familia_nina, familia.getId());
            realm.copyToRealm(familia8);
            Signo familia9 = new Signo("nino", R.drawable.familia_nino, familia.getId());
            realm.copyToRealm(familia9);
            Signo familia10 = new Signo("papa", R.drawable.familia_papa, familia.getId());
            realm.copyToRealm(familia10);
            Signo familia11 = new Signo("persona", R.drawable.familia_persona, familia.getId());
            realm.copyToRealm(familia11);
            Signo familia12 = new Signo("primo", R.drawable.familia_primo, familia.getId());
            realm.copyToRealm(familia12);
            Signo familia13 = new Signo("sordo", R.drawable.familia_sordo, familia.getId());
            realm.copyToRealm(familia13);
            Signo familia14 = new Signo("sordociego", R.drawable.familia_sordociego, familia.getId());
            realm.copyToRealm(familia14);
            Signo familia15 = new Signo("tio", R.drawable.familia_tio, familia.getId());
            realm.copyToRealm(familia15);

            Signo cuerpo1 = new Signo("boca", R.drawable.cuerpo_boca, cuerpo.getId());
            realm.copyToRealm(cuerpo1);
            Signo cuerpo2 = new Signo("brazo", R.drawable.cuerpo_brazo, cuerpo.getId());
            realm.copyToRealm(cuerpo2);
            Signo cuerpo3 = new Signo("cabeza", R.drawable.cuerpo_cabeza, cuerpo.getId());
            realm.copyToRealm(cuerpo3);
            Signo cuerpo4 = new Signo("cuerpo", R.drawable.cuerpo_cuerpo, cuerpo.getId());
            realm.copyToRealm(cuerpo4);
            Signo cuerpo5 = new Signo("culo", R.drawable.cuerpo_culo, cuerpo.getId());
            realm.copyToRealm(cuerpo5);
            Signo cuerpo6 = new Signo("dedo", R.drawable.cuerpo_dedo, cuerpo.getId());
            realm.copyToRealm(cuerpo6);
            Signo cuerpo7 = new Signo("dientes", R.drawable.cuerpo_dientes, cuerpo.getId());
            realm.copyToRealm(cuerpo7);
            Signo cuerpo8 = new Signo("lengua", R.drawable.cuerpo_lengua, cuerpo.getId());
            realm.copyToRealm(cuerpo8);
            Signo cuerpo9 = new Signo("mano", R.drawable.cuerpo_mano, cuerpo.getId());
            realm.copyToRealm(cuerpo9);
            Signo cuerpo10 = new Signo("nariz", R.drawable.cuerpo_nariz, cuerpo.getId());
            realm.copyToRealm(cuerpo10);
            Signo cuerpo11 = new Signo("ojo", R.drawable.cuerpo_ojo, cuerpo.getId());
            realm.copyToRealm(cuerpo11);
            Signo cuerpo12 = new Signo("oreja", R.drawable.cuerpo_oreja, cuerpo.getId());
            realm.copyToRealm(cuerpo12);
            Signo cuerpo13 = new Signo("pelo", R.drawable.cuerpo_pelo, cuerpo.getId());
            realm.copyToRealm(cuerpo13);
            Signo cuerpo14 = new Signo("pene", R.drawable.cuerpo_pene, cuerpo.getId());
            realm.copyToRealm(cuerpo14);
            Signo cuerpo15 = new Signo("pie", R.drawable.cuerpo_pie, cuerpo.getId());
            realm.copyToRealm(cuerpo15);
            Signo cuerpo16 = new Signo("pierna", R.drawable.cuerpo_pierna, cuerpo.getId());
            realm.copyToRealm(cuerpo16);
            Signo cuerpo17 = new Signo("vulva", R.drawable.cuerpo_vulva, cuerpo.getId());
            realm.copyToRealm(cuerpo17);
            Signo cuerpo18 = new Signo("gusto", R.drawable.cuerpo_gusto, cuerpo.getId());
            realm.copyToRealm(cuerpo18);
            Signo cuerpo19 = new Signo("oido", R.drawable.cuerpo_oido, cuerpo.getId());
            realm.copyToRealm(cuerpo19);
            Signo cuerpo20 = new Signo("olfato", R.drawable.cuerpo_olfato, cuerpo.getId());
            realm.copyToRealm(cuerpo20);
            Signo cuerpo21 = new Signo("sentidos", R.drawable.cuerpo_sentidos, cuerpo.getId());
            realm.copyToRealm(cuerpo21);
            Signo cuerpo22 = new Signo("tacto", R.drawable.cuerpo_tacto, cuerpo.getId());
            realm.copyToRealm(cuerpo22);
            Signo cuerpo23 = new Signo("vista", R.drawable.cuerpo_vista, cuerpo.getId());
            realm.copyToRealm(cuerpo23);

            Signo comidasYBebidas1 = new Signo("aceite", R.drawable.comidas_y_bebidas_aceite, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas1);
            Signo comidasYBebidas2 = new Signo("agua", R.drawable.comidas_y_bebidas_agua, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas2);
            Signo comidasYBebidas3 = new Signo("alimento", R.drawable.comidas_y_bebidas_alimento, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas3);
            Signo comidasYBebidas4 = new Signo("arroz", R.drawable.comidas_y_bebidas_arroz, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas4);
            Signo comidasYBebidas5 = new Signo("azucar", R.drawable.comidas_y_bebidas_azucar, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas5);
            Signo comidasYBebidas6 = new Signo("bebida", R.drawable.comidas_y_bebidas_bebida, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas6);
            Signo comidasYBebidas7 = new Signo("bocadillo", R.drawable.comidas_y_bebidas_bocadillo, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas7);
            Signo comidasYBebidas8 = new Signo("caramelo", R.drawable.comidas_y_bebidas_caramelo, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas8);
            Signo comidasYBebidas9 = new Signo("carnes", R.drawable.comidas_y_bebidas_carnes, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas9);
            Signo comidasYBebidas10 = new Signo("cebolla", R.drawable.comidas_y_bebidas_cebolla, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas10);
            Signo comidasYBebidas11 = new Signo("cena", R.drawable.comidas_y_bebidas_cena, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas11);
            Signo comidasYBebidas12 = new Signo("chocolate", R.drawable.comidas_y_bebidas_chocolate, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas12);
            Signo comidasYBebidas13 = new Signo("comida", R.drawable.comidas_y_bebidas_comida, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas13);
            Signo comidasYBebidas14 = new Signo("desayuno", R.drawable.comidas_y_bebidas_desayuno, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas14);
            Signo comidasYBebidas15 = new Signo("galleta", R.drawable.comidas_y_bebidas_galleta, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas15);
            Signo comidasYBebidas16 = new Signo("huevo", R.drawable.comidas_y_bebidas_huevo, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas16);
            Signo comidasYBebidas17 = new Signo("leche", R.drawable.comidas_y_bebidas_leche, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas17);
            Signo comidasYBebidas18 = new Signo("lechuga", R.drawable.comidas_y_bebidas_lechuga, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas18);
            Signo comidasYBebidas19 = new Signo("limon", R.drawable.comidas_y_bebidas_limon, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas19);
            Signo comidasYBebidas20 = new Signo("macarrones", R.drawable.comidas_y_bebidas_macarrones, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas20);
            Signo comidasYBebidas21 = new Signo("merienda", R.drawable.comidas_y_bebidas_merienda, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas21);
            Signo comidasYBebidas22 = new Signo("pan", R.drawable.comidas_y_bebidas_pan, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas22);
            Signo comidasYBebidas23 = new Signo("patata", R.drawable.comidas_y_bebidas_patata, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas23);
            Signo comidasYBebidas24 = new Signo("pescado", R.drawable.comidas_y_bebidas_pescado, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas24);
            Signo comidasYBebidas25 = new Signo("pollo", R.drawable.comidas_y_bebidas_pollo, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas25);
            Signo comidasYBebidas26 = new Signo("pure", R.drawable.comidas_y_bebidas_pure, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas26);
            Signo comidasYBebidas27 = new Signo("queso", R.drawable.comidas_y_bebidas_queso, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas27);
            Signo comidasYBebidas28 = new Signo("sal", R.drawable.comidas_y_bebidas_sal, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas28);
            Signo comidasYBebidas29 = new Signo("sed", R.drawable.comidas_y_bebidas_sed, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas29);
            Signo comidasYBebidas30 = new Signo("sopa", R.drawable.comidas_y_bebidas_sopa, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas30);
            Signo comidasYBebidas31 = new Signo("tomate", R.drawable.comidas_y_bebidas_tomate, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas31);
            Signo comidasYBebidas32 = new Signo("zanahoria", R.drawable.comidas_y_bebidas_zanahoria, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas32);
            Signo comidasYBebidas33 = new Signo("zumo", R.drawable.comidas_y_bebidas_zumo, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas33);
            Signo comidasYBebidas34 = new Signo("dulce", R.drawable.comidas_y_bebidas_postre, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas34);
            Signo comidasYBebidas35 = new Signo("flan", R.drawable.comidas_y_bebidas_flan, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas35);
            Signo comidasYBebidas36 = new Signo("fresa", R.drawable.comidas_y_bebidas_fresa, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas36);
            Signo comidasYBebidas37 = new Signo("fruta", R.drawable.comidas_y_bebidas_fruta, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas37);
            Signo comidasYBebidas38 = new Signo("helado", R.drawable.comidas_y_bebidas_helado, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas38);
            Signo comidasYBebidas39 = new Signo("manzana", R.drawable.comidas_y_bebidas_manzana, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas39);
            Signo comidasYBebidas40 = new Signo("naranja", R.drawable.comidas_y_bebidas_naranja, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas40);
            Signo comidasYBebidas41 = new Signo("pera", R.drawable.comidas_y_bebidas_pera, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas41);
            Signo comidasYBebidas42 = new Signo("platano", R.drawable.comidas_y_bebidas_platano, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas42);
            Signo comidasYBebidas43 = new Signo("postre", R.drawable.comidas_y_bebidas_postre, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas43);
            Signo comidasYBebidas44 = new Signo("sandia", R.drawable.comidas_y_bebidas_sandia, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas44);
            Signo comidasYBebidas45 = new Signo("tarta", R.drawable.comidas_y_bebidas_tarta, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas45);
            Signo comidasYBebidas46 = new Signo("uva", R.drawable.comidas_y_bebidas_uva, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas46);
            Signo comidasYBebidas47 = new Signo("yogur", R.drawable.comidas_y_bebidas_yogur, comidasYBebidas.getId());
            realm.copyToRealm(comidasYBebidas47);

            Signo colegio1 = new Signo("abecedario", R.drawable.colegio_abecedario, colegio.getId());
            realm.copyToRealm(colegio1);
            Signo colegio2 = new Signo("alumno", R.drawable.colegio_alumno, colegio.getId());
            realm.copyToRealm(colegio2);
            Signo colegio3 = new Signo("clase", R.drawable.colegio_clase, colegio.getId());
            realm.copyToRealm(colegio3);
            Signo colegio4 = new Signo("colegio", R.drawable.colegio_colegio, colegio.getId());
            realm.copyToRealm(colegio4);
            Signo colegio5 = new Signo("dibujo", R.drawable.colegio_dibujo, colegio.getId());
            realm.copyToRealm(colegio5);
            Signo colegio6 = new Signo("diferencia", R.drawable.colegio_diferencia, colegio.getId());
            realm.copyToRealm(colegio6);
            Signo colegio7 = new Signo("gramo", R.drawable.colegio_gramo, colegio.getId());
            realm.copyToRealm(colegio7);
            Signo colegio8 = new Signo("lenguajessignosespañola", R.drawable.colegio_lenguajessignosespa_ola, colegio.getId());
            realm.copyToRealm(colegio8);
            Signo colegio9 = new Signo("litro", R.drawable.colegio_litro, colegio.getId());
            realm.copyToRealm(colegio9);
            Signo colegio10 = new Signo("medida", R.drawable.colegio_medida, colegio.getId());
            realm.copyToRealm(colegio10);
            Signo colegio11 = new Signo("metro", R.drawable.colegio_metro, colegio.getId());
            realm.copyToRealm(colegio11);
            Signo colegio12 = new Signo("multiplicacion", R.drawable.colegio_multiplicacion, colegio.getId());
            realm.copyToRealm(colegio12);
            Signo colegio13 = new Signo("numero", R.drawable.colegio_numero, colegio.getId());
            realm.copyToRealm(colegio13);
            Signo colegio14 = new Signo("palabra", R.drawable.colegio_palabra, colegio.getId());
            realm.copyToRealm(colegio14);
            Signo colegio15 = new Signo("patio", R.drawable.colegio_patio, colegio.getId());
            realm.copyToRealm(colegio15);
            Signo colegio16 = new Signo("resta", R.drawable.colegio_resta, colegio.getId());
            realm.copyToRealm(colegio16);
            Signo colegio17 = new Signo("servicio", R.drawable.colegio_servicio, colegio.getId());
            realm.copyToRealm(colegio17);
            Signo colegio18 = new Signo("suma", R.drawable.colegio_suma, colegio.getId());
            realm.copyToRealm(colegio18);
            Signo colegio19 = new Signo("amarillo", R.drawable.colegio_amarillo, colegio.getId());
            realm.copyToRealm(colegio19);
            Signo colegio20 = new Signo("azul", R.drawable.colegio_azul, colegio.getId());
            realm.copyToRealm(colegio20);
            Signo colegio21 = new Signo("blanco", R.drawable.colegio_blanco, colegio.getId());
            realm.copyToRealm(colegio21);
            Signo colegio22 = new Signo("colores", R.drawable.colegio_colores, colegio.getId());
            realm.copyToRealm(colegio22);
            Signo colegio23 = new Signo("marron", R.drawable.colegio_marron, colegio.getId());
            realm.copyToRealm(colegio23);
            Signo colegio24 = new Signo("naranja", R.drawable.colegio_naranja, colegio.getId());
            realm.copyToRealm(colegio24);
            Signo colegio25 = new Signo("negro", R.drawable.colegio_negro, colegio.getId());
            realm.copyToRealm(colegio25);
            Signo colegio26 = new Signo("rojo", R.drawable.colegio_rojo, colegio.getId());
            realm.copyToRealm(colegio26);
            Signo colegio27 = new Signo("rosa", R.drawable.colegio_rosa, colegio.getId());
            realm.copyToRealm(colegio27);
            Signo colegio28 = new Signo("verde", R.drawable.colegio_verde, colegio.getId());
            realm.copyToRealm(colegio28);
            Signo colegio29 = new Signo("boligrafo", R.drawable.colegio_boligrafo, colegio.getId());
            realm.copyToRealm(colegio29);
            Signo colegio30 = new Signo("borrador", R.drawable.colegio_borrador, colegio.getId());
            realm.copyToRealm(colegio30);
            Signo colegio31 = new Signo("cera", R.drawable.colegio_cera, colegio.getId());
            realm.copyToRealm(colegio31);
            Signo colegio32 = new Signo("cosas-del-colegio", R.drawable.colegio_cosas_del_colegio, colegio.getId());
            realm.copyToRealm(colegio32);
            Signo colegio33 = new Signo("cosas", R.drawable.colegio_cosas, colegio.getId());
            realm.copyToRealm(colegio33);
            Signo colegio34 = new Signo("cuaderno", R.drawable.colegio_cuaderno, colegio.getId());
            realm.copyToRealm(colegio34);
            Signo colegio35 = new Signo("cuento", R.drawable.colegio_cuento, colegio.getId());
            realm.copyToRealm(colegio35);
            Signo colegio36 = new Signo("diccionario", R.drawable.colegio_diccionario, colegio.getId());
            realm.copyToRealm(colegio36);
            Signo colegio37 = new Signo("goma", R.drawable.colegio_goma, colegio.getId());
            realm.copyToRealm(colegio37);
            Signo colegio38 = new Signo("hoja", R.drawable.colegio_hoja, colegio.getId());
            realm.copyToRealm(colegio38);
            Signo colegio39 = new Signo("lapices-de-colores", R.drawable.colegio_lapices_de_colores, colegio.getId());
            realm.copyToRealm(colegio39);
            Signo colegio40 = new Signo("lapiz", R.drawable.colegio_lapiz, colegio.getId());
            realm.copyToRealm(colegio40);
            Signo colegio41 = new Signo("libro", R.drawable.colegio_libro, colegio.getId());
            realm.copyToRealm(colegio41);
            Signo colegio42 = new Signo("papel", R.drawable.colegio_papel, colegio.getId());
            realm.copyToRealm(colegio42);
            Signo colegio43 = new Signo("papelera", R.drawable.colegio_papelera, colegio.getId());
            realm.copyToRealm(colegio43);
            Signo colegio44 = new Signo("pegamento", R.drawable.colegio_pegamento, colegio.getId());
            realm.copyToRealm(colegio44);
            Signo colegio45 = new Signo("pintura", R.drawable.colegio_pintura, colegio.getId());
            realm.copyToRealm(colegio45);
            Signo colegio46 = new Signo("pizarra", R.drawable.colegio_pizarra, colegio.getId());
            realm.copyToRealm(colegio46);
            Signo colegio47 = new Signo("plastilina", R.drawable.colegio_plastilina, colegio.getId());
            realm.copyToRealm(colegio47);
            Signo colegio48 = new Signo("rotulador", R.drawable.colegio_rotulador, colegio.getId());
            realm.copyToRealm(colegio48);
            Signo colegio49 = new Signo("sacapuntas", R.drawable.colegio_sacapuntas, colegio.getId());
            realm.copyToRealm(colegio49);
            Signo colegio50 = new Signo("tijeras", R.drawable.colegio_tijeras, colegio.getId());
            realm.copyToRealm(colegio50);
            Signo colegio51 = new Signo("tiza", R.drawable.colegio_tiza, colegio.getId());
            realm.copyToRealm(colegio51);
            Signo colegio52 = new Signo("circulo", R.drawable.colegio_circulo, colegio.getId());
            realm.copyToRealm(colegio52);
            Signo colegio53 = new Signo("cuadrado", R.drawable.colegio_cuadrado, colegio.getId());
            realm.copyToRealm(colegio53);
            Signo colegio54 = new Signo("formas-y-tamanos", R.drawable.colegio_formas_y_tamanos, colegio.getId());
            realm.copyToRealm(colegio54);
            Signo colegio55 = new Signo("formas", R.drawable.colegio_formas, colegio.getId());
            realm.copyToRealm(colegio55);
            Signo colegio56 = new Signo("grande", R.drawable.colegio_grande, colegio.getId());
            realm.copyToRealm(colegio56);
            Signo colegio57 = new Signo("mediano", R.drawable.colegio_mediano, colegio.getId());
            realm.copyToRealm(colegio57);
            Signo colegio58 = new Signo("pequeno", R.drawable.colegio_pequeno, colegio.getId());
            realm.copyToRealm(colegio58);
            Signo colegio59 = new Signo("rectangulo", R.drawable.colegio_rectangulo, colegio.getId());
            realm.copyToRealm(colegio59);
            Signo colegio60 = new Signo("tamano", R.drawable.colegio_tamano, colegio.getId());
            realm.copyToRealm(colegio60);
            Signo colegio61 = new Signo("triangulo", R.drawable.colegio_triangulo, colegio.getId());
            realm.copyToRealm(colegio61);

            realm.commitTransaction();
            return new AtomicInteger(0);
        }
    }
}
